name: Test cargo-stow
on:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
      - 'Cargo.*'
      - '.github/workflows/cargo-stow.yaml'

jobs:
  test-build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository codeðŸ”Ž"
        uses: actions/checkout@v5
      - name: "Cache on cargo deps stuff"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${{ github.workspace }}/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo test --all-features
      - name: "Bootstrap install"
        run: cargo install --force --path .
      - name: Upload result artifact
        uses: actions/upload-artifact@v5
        with:
          name: cargo-stow-exec
          path: ~/.cargo/bin/cargo-stow

  build-example:
    defaults:
      run:
        shell: bash
        working-directory: ./cargo-stow/examples/greeter
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: "Check out repository codeðŸ”Ž"
        uses: actions/checkout@v5
      - name: Downlaod result artifact
        uses: actions/download-artifact@v5
        with:
          name: cargo-stow-exec
          path: ~/.cargo/bin/
      - run: chmod 755 ~/.cargo/bin/cargo-stow
      - run: ls -l ~/.cargo/bin
      - name: build example
        # run: cargo build
        run: cargo stow dockerfile
        env:
          RUST_LOG: info
      - name: build example
        # run: cargo build
        run: cargo stow build -d
        env:
          RUST_LOG: info
      - name: Run the image
        run: docker run --rm registry.example.org/directory/greeter:latest

  build-container:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: "Check out repository codeðŸ”Ž"
        uses: actions/checkout@v5
      - name: Downlaod result artifact
        uses: actions/download-artifact@v5
        with:
          name: cargo-stow-exec
          path: ~/.cargo/bin/
      - run: chmod 755 ~/.cargo/bin/cargo-stow
      - name: "Cache on cargo deps stuff"
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${{ github.workspace }}/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: "Generate Dockerfile"
        run: cargo stow dockerfile
        env:
          RUST_LOG: info
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
      # Using dockerf/build-push-action is the only solution for now
      - name: Build the container with and action
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: kuenishi/cargo-stow:latest
      # - name: Direct run of docker command, where GHA cache is not working
      #   run: docker buildx build -t registry.example.org/some/image --cache-from type=gha --cache-to type=gha,mode=max --output=type=docker --iidfile=target/build-iidfile.txt --metadata-file=target/build-metadata.json ${{ github.workspace }}/cargo-stow/
      #- name: Build the container with cargo-stow, where GHA cache is not working
      #  run: cargo stow build -d --cache-mode gha
      #  env:
      #    RUST_LOG: info
